### ISSUE TITLE
To-do items

### ISSUE THREAD

**Issue by TSSlade** [TSSlade/unesco_equity#1]
## Core Estimation
- [ ] Verify that survey weights have been applied to all estimations of means
- [ ] Add 95% CIs for estimation commands (gini, ineq. decomposition)
- [ ] Add _average fluency_ estimation back into apply_analysis command
- [ ] Add _sen's welfare_ estimation back into apply_analysis command
- [ ] Add _coefficient of variation_ estimation back into apply_analysis command
- [ ] Add 'eyeballed' cut-point analysis rather as contrast with benchmark-based analysis

## Additional Estimation
- [ ] Cluster by school to facilitate intuitive between- and within-group comparisons
- [ ] Develop SES tertile categorization (à la King et al) and do analyses by tertiles

## Output
- [ ] Adapt _apply analysis_ to have `svy` option and gracefully use weights (or not) as required
- [ ] Script out comparisons of metric X for groups Y, Z so reproducible, not Excel-based
    - **Tusome**
        - [ ] Comparison of Gini: Tusome Grade 1, baseline to midline
        - [ ] Comparison of Gini: Tusome Grade 2, baseline to midline
        - [ ] Comparison of ratio_p75p25: Tusome Grade 1, baseline to midline
        - [ ] Comparison of ratio_p75p25: Tusome Grade 2, baseline to midline
    - **PRIMR**
        - [ ] Comparison of Gini within Cohort: PRIMR Grade 1 English Cohort 1, baseline to endline
        - [ ] Comparison of Gini within Cohort: PRIMR Grade 1 English Cohort 2, baseline to endline
        - [ ] Comparison of Gini across Cohort at Endline: PRIMR Grade 1 English Cohort 1 vs Cohort 3, both at endline
        - [ ] Comparison of Gini across Cohort at Endline: PRIMR Grade 1 English Cohort 2 vs Cohort 3, both at endline
        - [ ] Comparison of Gini within Cohort: PRIMR Grade 2 English Cohort 1, baseline to endline
        - [ ] Comparison of Gini within Cohort: PRIMR Grade 2 English Cohort 2, baseline to endline
        - [ ] Comparison of Gini across Cohort at Endline: PRIMR Grade 2 English Cohort 1 vs Cohort 3, both at endline
        - [ ] Comparison of Gini across Cohort at Endline: PRIMR Grade 2 English Cohort 2 vs Cohort 3, both at endline
        - [ ] Comparison of ratio_p75p25 within Cohort: PRIMR Grade 1 English Cohort 1, baseline to endline
        - [ ] Comparison of ratio_p75p25 within Cohort: PRIMR Grade 1 English Cohort 2, baseline to endline
        - [ ] Comparison of ratio_p75p25 across Cohort at Endline: PRIMR Grade 1 English Cohort 1 vs Cohort 3, both at endline
        - [ ] Comparison of ratio_p75p25 across Cohort at Endline: PRIMR Grade 1 English Cohort 2 vs Cohort 3, both at endline
        - [ ] Comparison of ratio_p75p25 within Cohort: PRIMR Grade 2 English Cohort 1, baseline to endline
        - [ ] Comparison of ratio_p75p25 within Cohort: PRIMR Grade 2 English Cohort 2, baseline to endline
        - [ ] Comparison of ratio_p75p25 across Cohort at Endline: PRIMR Grade 2 English Cohort 1 vs Cohort 3, both at endline
        - [ ] Comparison of ratio_p75p25 across Cohort at Endline: PRIMR Grade 2 English Cohort 2 vs Cohort 3, both at endline

## To Confirm with Luis
- [ ] Need for
