### ISSUE TITLE
Mavzuna's To-Do List

### ISSUE THREAD

**Issue by TSSlade** [TSSlade/unesco_equity#3]
# Tasks for Mavzuna during her internship
- [ ] Replicate Kenya Tusome, PRIMR analyses from Crouch & Slade 2020
- [ ] Review literature associated with inequality calculations for ordinal measures
- [ ] Apply inequality-based analytical lens to ASER Pakistan data

**Comment by TSSlade** [comment]
We closed this as an exercise for @lcrouch1952 in how to interact with the system. Now, @mavzunat , I am reopening it so you can 
+ receive a notification to this effect, and
+ see a trivial example of how the `Issues` function can be used
